### ISSUE TITLE
Recorder: problem when edit recordings

### ISSUE THREAD

**Issue by silviabf** [teltek/Galicaster#311]
Steps:
- Go to recorder
- Launch a recording
- Click on edit and then in save

Problem: the edit window does not close and galicaster is blocked. In the console i have the next message:
```
TypeError: __check_recording_started() takes exactly 2 arguments (3 given)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Traceback (most recent call last):
  File "/home/galicaster/galicaster_public/galicaster/classui/recorderui.py", line 425, in on_edit_meta
    Metadata(self.recorder.current_mediapackage, parent=self)
  File "/home/galicaster/galicaster_public/galicaster/classui/metadata.py", line 153, in __init__
    self.update_metadata(table,package)
  File "/home/galicaster/galicaster_public/galicaster/classui/metadata.py", line 253, in update_metadata
    series = utils_series.filterSeriesbyId(self.series_list, identifier)
  File "/home/galicaster/galicaster_public/galicaster/opencast/series.py", line 111, in filterSeriesbyId
    match = {"id": seriesid, "name": list_series[seriesid]['title'], "list": list_series[seriesid]}
TypeError: list indices must be integers, not NoneType

```

**Comment by silviabf** [comment]
The bug is solved. I close this issue.
