### ISSUE TITLE
When there is an error during the recording the resultant recording is deleted

### ISSUE THREAD

**Issue by hcaloto** [teltek/Galicaster#345]
After reloading a profile, the resultant files are overwritten

**Comment by silviabf** [comment]
Galicaster saves the recording after reload the profile but there is an error when you stop the next recording.

Steps:
- Launch galicaster and select a webcam profile
- Launch a recording
- Unplug the webcam
- Plug again the webcam and reload the profile (button reload)
- Go to mediamanager and play the recovered recording
- Go to recorder and start a recording
- Stop the recording

Problem: Galicaster is blocked after you push stop. In the console you can see the next information:
```
Traceback (most recent call last):
  File "/usr/share/galicaster/galicaster/classui/message.py", line 415, in on_dialog_response
    self.response_action(response_id, builder=self.gui, popup=self)
  File "/usr/share/galicaster/galicaster/classui/recorderui.py", line 284, in on_stop_dialog_response
    self.recorder.stop()
  File "/usr/share/galicaster/galicaster/recorder/service.py", line 186, in stop
    self.__close_mp()
  File "/usr/share/galicaster/galicaster/recorder/service.py", line 198, in __close_mp
    close_duration, self.current_mediapackage.manual)
  File "/usr/share/galicaster/galicaster/mediapackage/repository.py", line 565, in add_after_rec
    dest = os.path.join(mp.getURI(), os.path.basename(filename))
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "/usr/share/galicaster/galicaster/classui/message.py", line 415, in on_dialog_response
    self.response_action(response_id, builder=self.gui, popup=self)
  File "/usr/share/galicaster/galicaster/classui/recorderui.py", line 284, in on_stop_dialog_response
    self.recorder.stop()
  File "/usr/share/galicaster/galicaster/recorder/service.py", line 186, in stop
    self.__close_mp()
  File "/usr/share/galicaster/galicaster/recorder/service.py", line 198, in __close_mp
    close_duration, self.current_mediapackage.manual)
  File "/usr/share/galicaster/galicaster/mediapackage/repository.py", line 565, in add_after_rec
    dest = os.path.join(mp.getURI(), os.path.basename(filename))
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```
And in the galicaster log:

```
galicaster	2016-07-11 12:07:08,302	ERROR	recorder/recorder	gst-resource-error-quark: Could not read from resource. (9) (gstv4l2bufferpool.c(1054): gst_v4l2_buffer_pool_poll (): /Gs
tPipeline:galicaster_recorder/galicaster+recorder+bins+v4l2+GCv4l2:galicaster+recorder+bins+v4l2+gcv4l2-11/GstBin:bin18/GstV4l2Src:gc-v4l2-src:
poll error 1: Invalid argument (22))
galicaster	2016-07-11 12:07:08,737	ERROR	recorder/service	Handle error (gst-resource-error-quark: Could not read from resource. (9) (gstv4l2bufferpool.c(1054): gst_v4l2_buffer_poo
l_poll (): /GstPipeline:galicaster_recorder/galicaster+recorder+bins+v4l2+GCv4l2:galicaster+recorder+bins+v4l2+gcv4l2-11/GstBin:bin18/GstV4l2Src:gc-v4l2-src:
poll error 1: Invalid argument (22)))

```

**Comment by silviabf** [comment]
It is correctly working now. I close this issue
