### ISSUE TITLE
Info dialog does not work for scheduled recordings

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#415]
GC 2.x, latest code.

Schedule a recording via Opencast. In the Media Manager, right-click and choose Info. Nothing happens. Console error:

Traceback (most recent call last):
  File "/usr/share/galicaster/galicaster/classui/listing.py", line 438, in on_info
    self.info(key)
  File "/usr/share/galicaster/galicaster/classui/managerui.py", line 256, in info
    close_on_response=False)
  File "/usr/share/galicaster/galicaster/classui/message.py", line 95, in __init__
    self.dialog = self.configure_ui(text, message, self.gui, parent)
  File "/usr/share/galicaster/galicaster/classui/message.py", line 205, in configure_ui
    series_frame.show()
AttributeError: 'NoneType' object has no attribute 'show'

This does not happen for an unscheduled recording - info displays fine then.

A similar error happens for scheduled recordings that were recorded with GC 1.4.x prior to upgrading to GC 2.x, with a different cause:

Traceback (most recent call last):
  File "/usr/share/galicaster/galicaster/classui/listing.py", line 438, in on_info
    self.info(key)
  File "/usr/share/galicaster/galicaster/classui/managerui.py", line 251, in info
    text = self.get_mp_info(key)
  File "/usr/share/galicaster/galicaster/classui/managerui.py", line 279, in get_mp_info
    data = set_manifest_json(mp)
  File "/usr/share/galicaster/galicaster/mediapackage/serializer.py", line 363, in set_manifest_json
    mp_json['series{}'.format(data)] = mp.series_episode[data]
AttributeError: 'Mediapackage' object has no attribute 'series_episode'

**Comment by smarquard** [comment]
Fixed, thanks!

**Comment by silviabf** [comment]
Fixed. I close this issue. Thanks @smarquard !
