### ISSUE TITLE
Galicaster doesn't like W3CDTF timestamps with offset

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#471]
If you schedule a recording in OC 2.x through a REST endpoint with a script that creates DC XML like:

<dcterms:temporal>start=2017-03-07T09:44:00+02:00; end=2017-03-07T09:45:00+02:00; scheme=W3C-DTF;</dcterms:temporal> 

then the recording subsequently fails on Galicaster. It seems Galicaster doesn't like the +02:00 timestamp here and only works with W3CDTF timestamps that end in Z, e.g.

<dcterms:temporal>start=2017-03-07T08:00:00Z; end=2017-03-07T08:01:00Z; scheme=W3C-DTF;</dcterms:temporal> 

although the first format is valid W3CDTF.

The consequence of this is that Galicaster does not calculate the duration, and so you get a manifest.xml file without a duration in the mediapackage element.

You then get other errors like these below, and Galicaster does not record the event or list it in the UI.

```
Traceback (most recent call last):
  File "/usr/share/galicaster/galicaster/scheduler/scheduler.py", line 105, in __start_record
    GObject.timeout_add_seconds(mp.getDuration()/1000, self.__stop_record, mp.getIdentifier())
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/share/galicaster/galicaster/classui/listing.py", line 87, in event_change_mode
    self.refresh()
  File "/usr/share/galicaster/galicaster/classui/listing.py", line 273, in refresh
    self.refresh_treeview()
  File "/usr/share/galicaster/galicaster/classui/listing.py", line 227, in refresh_treeview
    self.insert_data_in_list(self.lista, self.repository.list().values())
  File "/usr/share/galicaster/galicaster/classui/listing.py", line 93, in insert_data_in_list
    duration = round(mp.getDuration(), -3)
TypeError: a float is required
```

**Comment by Alfro** [comment]
Thanks Stephen. We'll take a look at this.

**Comment by Alfro** [comment]
Just a quick update. We were able to reproduce this, and my colleague @dpeite is already working on a solution.
Cheers!

**Comment by Alfro** [comment]
Galicaster mediapackage dates don't have timezone information internally, and the xml parser would assume incorrectly that all date would come in UTC timezone.
We simply corrected that and convert all dates to UTC before stripping of the timezone info.
@smarquard It shouldn't give an error now.
