### ISSUE TITLE
Tests fail when [ingest] manual config option set to nightly/immediately

### ISSUE THREAD

**Issue by pmgration** [teltek/Galicaster#580]
With `[ingest]` `manual` config option set to either `nightly` or `immediately` then running `make test` I get the following errors:

`Immediately`
```
======================================================================
ERROR: test_new_recording_when_paused (tests.recorder.service.TestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/dev/galicaster/tests/recorder/service.py", line 278, in test_new_recording_when_paused
    recorder_service.record()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 156, in record
    self.__close_mp()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 214, in __close_mp
    self.enqueue_ingest(self.current_mediapackage)
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 223, in enqueue_ingest
    self.worker.enqueue_job_by_name('ingest', mp)
AttributeError: 'WorkerMock' object has no attribute 'enqueue_job_by_name'

======================================================================
ERROR: test_new_recording_when_recording (tests.recorder.service.TestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/dev/galicaster/tests/recorder/service.py", line 239, in test_new_recording_when_recording
    recorder_service.record()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 156, in record
    self.__close_mp()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 214, in __close_mp
    self.enqueue_ingest(self.current_mediapackage)
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 223, in enqueue_ingest
    self.worker.enqueue_job_by_name('ingest', mp)
AttributeError: 'WorkerMock' object has no attribute 'enqueue_job_by_name'

======================================================================
ERROR: test_new_recording_when_recording_not_allow (tests.recorder.service.TestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/dev/galicaster/tests/recorder/service.py", line 262, in test_new_recording_when_recording_not_allow
    recorder_service.stop()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 197, in stop
    self.__close_mp()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 214, in __close_mp
    self.enqueue_ingest(self.current_mediapackage)
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 223, in enqueue_ingest
    self.worker.enqueue_job_by_name('ingest', mp)
AttributeError: 'WorkerMock' object has no attribute 'enqueue_job_by_name'

======================================================================
ERROR: test_record_scheduled_mp (tests.recorder.service.TestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/dev/galicaster/tests/recorder/service.py", line 302, in test_record_scheduled_mp
    recorder_service.stop()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 197, in stop
    self.__close_mp()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 214, in __close_mp
    self.enqueue_ingest(self.current_mediapackage)
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 223, in enqueue_ingest
    self.worker.enqueue_job_by_name('ingest', mp)
AttributeError: 'WorkerMock' object has no attribute 'enqueue_job_by_name'

======================================================================
ERROR: test_recording (tests.recorder.service.TestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/dev/galicaster/tests/recorder/service.py", line 149, in test_recording
    recorder_service.stop()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 197, in stop
    self.__close_mp()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 214, in __close_mp
    self.enqueue_ingest(self.current_mediapackage)
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 223, in enqueue_ingest
    self.worker.enqueue_job_by_name('ingest', mp)
AttributeError: 'WorkerMock' object has no attribute 'enqueue_job_by_name'

======================================================================
ERROR: test_stop_recoding_on_pause (tests.recorder.service.TestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/dev/galicaster/tests/recorder/service.py", line 173, in test_stop_recoding_on_pause
    recorder_service.stop()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 197, in stop
    self.__close_mp()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 214, in __close_mp
    self.enqueue_ingest(self.current_mediapackage)
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 223, in enqueue_ingest
    self.worker.enqueue_job_by_name('ingest', mp)
AttributeError: 'WorkerMock' object has no attribute 'enqueue_job_by_name'

----------------------------------------------------------------------
Ran 181 tests in 25.276s

FAILED (SKIP=6, errors=6)
Makefile:34: recipe for target 'test' failed
make: *** [test] Error 1
```

`Nightly`
```
======================================================================
ERROR: test_new_recording_when_paused (tests.recorder.service.TestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/dev/galicaster/tests/recorder/service.py", line 278, in test_new_recording_when_paused
    recorder_service.record()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 156, in record
    self.__close_mp()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 214, in __close_mp
    self.enqueue_ingest(self.current_mediapackage)
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 225, in enqueue_ingest
    self.worker.enqueue_nightly_job_by_name('ingest', mp)
AttributeError: 'WorkerMock' object has no attribute 'enqueue_nightly_job_by_name'

======================================================================
ERROR: test_new_recording_when_recording (tests.recorder.service.TestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/dev/galicaster/tests/recorder/service.py", line 239, in test_new_recording_when_recording
    recorder_service.record()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 156, in record
    self.__close_mp()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 214, in __close_mp
    self.enqueue_ingest(self.current_mediapackage)
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 225, in enqueue_ingest
    self.worker.enqueue_nightly_job_by_name('ingest', mp)
AttributeError: 'WorkerMock' object has no attribute 'enqueue_nightly_job_by_name'

======================================================================
ERROR: test_new_recording_when_recording_not_allow (tests.recorder.service.TestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/dev/galicaster/tests/recorder/service.py", line 262, in test_new_recording_when_recording_not_allow
    recorder_service.stop()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 197, in stop
    self.__close_mp()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 214, in __close_mp
    self.enqueue_ingest(self.current_mediapackage)
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 225, in enqueue_ingest
    self.worker.enqueue_nightly_job_by_name('ingest', mp)
AttributeError: 'WorkerMock' object has no attribute 'enqueue_nightly_job_by_name'

======================================================================
ERROR: test_record_scheduled_mp (tests.recorder.service.TestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/dev/galicaster/tests/recorder/service.py", line 302, in test_record_scheduled_mp
    recorder_service.stop()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 197, in stop
    self.__close_mp()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 214, in __close_mp
    self.enqueue_ingest(self.current_mediapackage)
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 225, in enqueue_ingest
    self.worker.enqueue_nightly_job_by_name('ingest', mp)
AttributeError: 'WorkerMock' object has no attribute 'enqueue_nightly_job_by_name'

======================================================================
ERROR: test_recording (tests.recorder.service.TestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/dev/galicaster/tests/recorder/service.py", line 149, in test_recording
    recorder_service.stop()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 197, in stop
    self.__close_mp()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 214, in __close_mp
    self.enqueue_ingest(self.current_mediapackage)
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 225, in enqueue_ingest
    self.worker.enqueue_nightly_job_by_name('ingest', mp)
AttributeError: 'WorkerMock' object has no attribute 'enqueue_nightly_job_by_name'

======================================================================
ERROR: test_stop_recoding_on_pause (tests.recorder.service.TestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/dev/galicaster/tests/recorder/service.py", line 173, in test_stop_recoding_on_pause
    recorder_service.stop()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 197, in stop
    self.__close_mp()
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 214, in __close_mp
    self.enqueue_ingest(self.current_mediapackage)
  File "/home/paul/dev/galicaster/galicaster/recorder/service.py", line 225, in enqueue_ingest
    self.worker.enqueue_nightly_job_by_name('ingest', mp)
AttributeError: 'WorkerMock' object has no attribute 'enqueue_nightly_job_by_name'

----------------------------------------------------------------------
Ran 181 tests in 47.410s

FAILED (SKIP=6, errors=6)
Makefile:34: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by dpeite** [comment]
Fixed, thanks!
